spring.application.name=pharmacy
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy
spring.datasource.username=root
spring.datasource.password=Guna@0040

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
